Repository swift-server/RediStack, pull requests merged in 2023-06, with the labels that each got.

#54 Add swift-server CI
  docker/Dockerfile
  docker/docker-compose.2004.56.yaml
  docker/docker-compose.2204.57.yaml
  docker/docker-compose.2204.58.yaml
  docker/docker-compose.2204.59.yaml
  docker/docker-compose.2204.main.yaml
  docker/docker-compose.yaml
Labels: semver/none

#52 Fix crash in tests: Use explicit RedisCommand instead of tuple
  Sources/RediStackTestUtils/RedisConnectionPoolIntegrationTestCase.swift
  Tests/RediStackIntegrationTests/RedisConnectionPoolTests.swift
  Tests/RediStackTests/ChannelHandlers/RedisCommandHandlerTests.swift
Labels: semver/none

#58 Add scripts for better CI
  Sources/RediStack/RESP/RESPTranslator.swift
  Tests/LinuxMain.swift
  docs/theme/assets/css/highlight.css.scss
  docs/theme/assets/css/jazzy.css.scss
  docs/theme/assets/img/carat.png
  docs/theme/assets/img/dash.png
  docs/theme/assets/img/gl.png
  docs/theme/assets/img/spinner.gif
  docs/theme/assets/js/jazzy.js
  docs/theme/assets/js/jazzy.search.js
  docs/theme/assets/js/jquery.min.js
  docs/theme/assets/js/lunr.min.js
  docs/theme/assets/js/typeahead.jquery.js
  docs/theme/templates/deprecation.mustache
  docs/theme/templates/doc.mustache
  docs/theme/templates/footer.mustache
  docs/theme/templates/header.mustache
  docs/theme/templates/nav.mustache
  docs/theme/templates/parameter.mustache
  docs/theme/templates/task.mustache
  docs/theme/templates/tasks.mustache
  scripts/check_no_api_breakages.sh
  scripts/soundness.sh
Labels: semver/none

#57 Explicitly depend on Atomics
  Package.swift
Labels: semver/patch

#53 Remove GitHub funding and issue and pr template
  .github/FUNDING.yml
  .github/issue_template.md
  .github/pull_request_template.md
Labels: semver/none

#55 Remove `.codeclimate` file
  .codeclimate.yml
  README.md
Labels: semver/none

#60 Remove reliance on the NIO umbrella module
  Package.swift
  README.md
  Sources/RediStack/ChannelHandlers/RedisByteDecoder.swift
  Sources/RediStack/ChannelHandlers/RedisCommandHandler.swift
  Sources/RediStack/ChannelHandlers/RedisMessageEncoder.swift
  Sources/RediStack/ChannelHandlers/RedisPubSubHandler.swift
  Sources/RediStack/Commands/BasicCommands.swift
  Sources/RediStack/Commands/HashCommands.swift
  Sources/RediStack/Commands/ListCommands.swift
  Sources/RediStack/Commands/PubSubCommands.swift
  Sources/RediStack/Commands/SetCommands.swift
  Sources/RediStack/Commands/SortedSetCommands.swift
  Sources/RediStack/Commands/StringCommands.swift
  Sources/RediStack/Configuration.swift
  Sources/RediStack/ConnectionPool/ConnectionPool.swift
  Sources/RediStack/Extensions/SwiftNIO.swift
  Sources/RediStack/RESP/RESPTranslator.swift
  Sources/RediStack/RESP/RESPValue.swift
  Sources/RediStack/RedisClient.swift
  Sources/RediStack/RedisConnection.swift
  Sources/RediStack/RedisConnectionPool.swift
  Sources/RediStack/RedisKey+TTL.swift
  Sources/RediStack/RedisLogging.swift
  Sources/RediStack/_Deprecations.swift
  Sources/RediStackTestUtils/EmbeddedMockRedisServer.swift
  Sources/RediStackTestUtils/Extensions/General.swift
  Sources/RediStackTestUtils/Extensions/RediStack.swift
  Sources/RediStackTestUtils/RedisConnectionPoolIntegrationTestCase.swift
  Sources/RediStackTestUtils/RedisIntegrationTestCase.swift
  Sources/RediStackTestUtils/_Deprecations.swift
  Sources/RedisTypes/RedisSet.swift
  Tests/RediStackIntegrationTests/Commands/PubSubCommandsTests.swift
  Tests/RediStackIntegrationTests/Commands/SortedSetCommandsTests.swift
  Tests/RediStackIntegrationTests/RedisConnectionPoolTests.swift
  Tests/RediStackTests/ChannelHandlers/RedisByteDecoderTests.swift
  Tests/RediStackTests/ChannelHandlers/RedisMessageEncoderTests.swift
  Tests/RediStackTests/ConfigurationTests.swift
  Tests/RediStackTests/ConnectionPoolTests.swift
  Tests/RediStackTests/RESPTranslatorTests.swift
  Tests/RediStackTests/RedisConnectionTests.swift
  scripts/soundness.sh
Labels: semver/patch

#65 Require Swift 5.6
  Package.swift
  Sources/RediStack/RedisClient.swift
Labels: semver/minor

#64 Delay connection attempts without addresses.
  Sources/RediStack/ConnectionPool/ConnectionPool.swift
  Sources/RediStack/RedisConnectionPool.swift
  Sources/RediStackTestUtils/RedisConnectionPoolIntegrationTestCase.swift
  Tests/RediStackIntegrationTests/RedisConnectionPoolTests.swift
Labels: semver/patch

#63 Conform `RedisByteDecoder` to `NIOSingleStepByteToMessageDecoder`
  Sources/RediStack/ChannelHandlers/RedisByteDecoder.swift
Labels: semver/minor

#62 README: Remove the testing table, release table and supported OSes
  README.md
Labels: semver/none

#66 Remove GitLab CI
  .gitlab/ci/centos-7.yml
  .gitlab/ci/eol-platforms-5.5.yml
  .gitlab/ci/main.yml
  .gitlab/ci/platform-test.yml
  .gitlab/ci/standard-platforms.yml
Labels: semver/none

#56 README.md: Switch mirroring around
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  Sources/RediStack/RESP/RESPTranslator.swift
Labels: semver/none
